name: ESLint
on: push
jobs:
  ESLint:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: ci
        run: cd NodeServer && yarn install --immutable --immutable-cache --check-cache
      - name: ESLint
        run: cd NodeServer && yarn lint
