name: NodeServer-mocha-test
on: push
jobs:
  mocha:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: ci
        run: cd NodeServer && yarn install --immutable --immutable-cache --check-cache
      - name: build
        run: cd NodeServer && export NODE_ENV=test && yarn build
      - name: mocha
        run: cd NodeServer && yarn test:mocha
